### ISSUE TITLE
Consul support

### ISSUE THREAD

**Issue by Difrex** [Surkoveds/surok#12]
Is it really needed in surok?
Just DNS queries(it is simple to add) or KV discovery?

**Comment by Difrex** [comment]
Look at #13

**Comment by Difrex** [comment]
May be move Consul section to service config?

**Comment by w1r0x** [comment]
I think it can be good option for surok, because many services using consul in mesos environment.

**Comment by w1r0x** [comment]
#13 is good enough. Should we add discovery via consul api?
